@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=api
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}

### Route GET /categories

GET {{baseUrl}}/categories

### Route GET /products

GET {{baseUrl}}/products

### Route GET /product/:id

GET {{baseUrl}}/product/3

### Route POST /signup

POST {{baseUrl}}/signup
Content-Type: application/json

{
    "email": "jaybi@gmail.fr",
    "password": "bla",
    "passwordConfirm" : "bla",
    "last_name": "Bataya",
    "first_name": "Hernandez",
    "phone_number": "0602235645"
}

### Route POST /login

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "jaybi@gmail.fr",
    "password": "bla"
}

### Route POST /category

POST {{baseUrl}}/category
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImlhdCI6MTYxNDk1Mjk5MCwiZXhwIjoxNjE0OTYzNzkwfQ.-Tbyt2fiTrXwgDMWahjlFvf8oiAbNkqM1F4-ErWy8Z0

{
    "label": "Sandwich",
    "image": "Un bon petit burger américain là"
}

### Route PUT /category

PUT {{baseUrl}}/category
Content-Type: application/json

{
    "id":"5",
    "label": "Sandwich",
    "image": "Un bon sandwich au paté"
}

### Route PUT /category

DELETE {{baseUrl}}/category
Content-Type: application/json

{
    "id":"4" 
}

### Route POST /product

POST {{baseUrl}}/product
Content-Type: application/json

{
    "title": "Panini Nutella",
    "description": "Le meilleur panini du monde",
    "price": 1.95,
    "image": "image d'huile de palme",
    "categories" : [1,5]
}

### Route PUT /product

PUT {{baseUrl}}/product
Content-Type: application/json

{
    "id" : 9,
    "title": "AIEAIE",
    "description": "Incroyable panini du monde",
    "price": 1.95,
    "image": "image d'huile de palme",
    "categories" : [1,2,5]
}

### Route DELETE /product

DELETE {{baseUrl}}/product
Content-Type: application/json

{
    "id" : 9
}

### Route POST /allergen

POST {{baseUrl}}/allergen
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImlhdCI6MTYxNDk1Mjk5MCwiZXhwIjoxNjE0OTYzNzkwfQ.-Tbyt2fiTrXwgDMWahjlFvf8oiAbNkqM1F4-ErWy8Z0

{
    "name": "moutarde",
    "color": "#ff00ff"
}

### Route PUT /allergen

PUT {{baseUrl}}/allergen
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImlhdCI6MTYxNDk1Mjk5MCwiZXhwIjoxNjE0OTYzNzkwfQ.-Tbyt2fiTrXwgDMWahjlFvf8oiAbNkqM1F4-ErWy8Z0

{
    "id":1,
    "name": "moutarde",
    "color": "#ffe436"
}

### Route PUT /allergen

DELETE {{baseUrl}}/allergen
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImlhdCI6MTYxNDk1Mjk5MCwiZXhwIjoxNjE0OTYzNzkwfQ.-Tbyt2fiTrXwgDMWahjlFvf8oiAbNkqM1F4-ErWy8Z0

{
    "id":1
}
